### LOCAL REQUESTS

### PING
GET http://localhost:8000/
Content-Type: application/json
###

### CREATE TASK
POST http://localhost:8000/v1/task
Content-Type: application/json

{
    "title": "It's the day",
    "description": "I don't remember what I have to do",
    "status": "Pending"
}
###

### GET ALL TASKS
GET http://localhost:8000/v1/tasks
Content-Type: application/json
###

### GET TASK BY ID
GET http://localhost:8000/v1/task/4da7d067-0769-4ef8-b988-37edf1e320ed
Content-Type: application/json
###

### UPDATE TASK
PATCH http://localhost:8000/v1/task/4da7d067-0769-4ef8-b988-37edf1e320ed
Content-Type: application/json

{
  "title": "Ravi",
  "description": "Uma outra Description da Ravi",
  "status": "pending"
}

### DELETE TASK
DELETE http://localhost:8000/v1/task/3e58b863-f30f-4dde-9858-46043aa75060
Content-Type: application/json
###