name: Dependabot auto-approval

on:
    pull_request:
        branches:
            - dependabot/*
        types:
            - opened
            - synchronize
            - reopened
        
permissions:
    contents: read
    pull-requests: write

jobs:
    dependabot:
        runs-on: ubuntu-latest
        if: github.actor == 'dependabot[bot]'

        name: CI
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-python@v5
              with:
                  python-version-file: ".python-version"
            - uses: actions/cache@v4
              id: cache
              with:
                  path: /opt/hostedtoolcache/Python/
                  key: poetry-${{ hashFiles('**/poetry.lock') }}
                  restore-keys: poetry-
            - run: make dev-dependencies
              env: 
                  POETRY_VIRTUALENVS_CREATE: false
            - run: make lint

    approve_on_success:
        runs-on: ubuntu-latest
        needs: [dependabot]
        steps:
            - name: Approve pull request if checks pass
              run: |
                if [[ ${{ needs.dependabot.result }} == 'success' ]]; then gh pr review --approve "$PR_URL" --approve; fi
                env:
                    PR_URL: ${{ github.event.pull_request.html_url }}
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}