name: Dependabot auto-approve
on: pull_request
        
permissions:
    pull-requests: write
    contents: write

jobs:              
    ci:
        name: CI - Build
        runs-on: ubuntu-latest
        if: github.actor == 'dependabot[bot]'
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-python@v5
              with:
                  python-version-file: ".python-version"
            - uses: actions/cache@v4
              id: cache
              with:
                  path: /opt/hostedtoolcache/Python/
                  key: poetry-${{ hashFiles('**/poetry.lock') }}
                  restore-keys: poetry-
            - run: make dev-dependencies
              env: 
                  POETRY_VIRTUALENVS_CREATE: false
            - run: make lint

    approve_on_success:
        name: Approve pull request
        runs-on: ubuntu-latest
        needs: [ci]
        steps:
            - name: Dependabot metadata
              id: metadata
              uses: dependabot/fetch-metadata@v2
              with:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            - name: Approve pull request if checks pass
              run: gh pr review --approve "$PR_URL"
              env:
                PR_URL: ${{ github.event.pull_request.html_url }}
                GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}