on:
    push:
        branches:
            - main
        tags:
            - "*"
        paths-ignore:
            - "**/*.md"

    pull_request:
        branches:
            - "*"
        paths-ignore:
            - "**/*.md"
    workflow_dispatch:

name: Standard

jobs:
    ci:
        name: CI - Build
        runs-on: ubuntu-latest
        if: github.actor != 'dependabot[bot]'
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-python@v5
              with:
                  python-version-file: ".python-version"
            - uses: actions/cache@v4
              id: cache
              with:
                  path: /opt/hostedtoolcache/Python/
                  key: poetry-${{ hashFiles('**/poetry.lock') }}
                  restore-keys: poetry-
            - run: make dev-dependencies
              env: 
                  POETRY_VIRTUALENVS_CREATE: false
            - run: make lint
